# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=256)),
                ('org_name', models.CharField(max_length=256)),
            ],
        ),
    ]
